version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: acantilado-sur-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: c2101314_testing
      MYSQL_USER: c2101314_testing
      MYSQL_PASSWORD: nekesuBU83
    volumes:
      - acantilado_sur_db_data:/var/lib/mysql
    restart: unless-stopped

  web:
    build: .
    container_name: acantilado-sur-web
    ports:
      - "8101:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=c2101314_testing
      - DB_USERNAME=c2101314_testing
      - DB_PASSWORD=nekesuBU83
    depends_on:
      - db
    restart: unless-stopped

volumes:
  acantilado_sur_db_data:
